Repository juanitorduz/btsa, pull requests merged in 2020-10, with the labels that each got.

#20 Intro DeepAR with GluonTS from Docs
  python/deepAR/deepAR_gluonts_example.ipynb
  resources.md
Labels: documentation, enhancement

#22 Fix python libraries versions on Docker
  .github/workflows/dockerimage.yml
  README.md
  environment.yml
  requirements.txt
Labels: bug

#23 add binder link
  README.md
Labels: enhancement

#24 correct typo deepAr example notebook
  python/deepAR/deepAR_gluonts_example.ipynb
Labels: bug

#25 Deep ar session
  environment.yml
  python/deepAR/DeepAR GlueonTS PyTorchTS comparison.ipynb
Labels: enhancement

#26 add model evaluation plots to deepAr example notebook
  python/deepAR/deepAR_gluonts_example.ipynb
Labels: enhancement
